name: Build and Test

on:
    push:
        branches:
            - master
        tags:
            - v*
    pull_request:
        branches:
            - master
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 2 # See: https://github.com/codecov/codecov-action/issues/190

            - uses: actions/setup-java@v2
              with:
                distribution: 'adopt'
                java-version: '8'

            - name: Build and test
              shell: bash
              env:
                WHITESOURCE_API_KEY: ${{ secrets.WHITESOURCE_API_KEY }}
                JACOCO_COVERAGE: true
              run: ./scripts/run_gh_actions.sh

            - name: Publish code coverage
              uses: codecov/codecov-action@v1
              with:
                files: jacoco.xml # This report is copied over from target/jacoco-ut after building
                fail_ci_if_error: false

